export const ADD_UNIT_REQUEST = "ADD_UNIT_REQUEST";
export const ADD_UNIT_SUCCESS = "ADD_UNIT_SUCCESS";
export const ADD_UNIT_FAILURE = "ADD_UNIT_FAILURE";

export const DELETE_UNIT_REQUEST = "DELETE_UNIT_REQUEST";
export const DELETE_UNIT_SUCCESS = "DELETE_UNIT_SUCCESS";
export const DELETE_UNIT_FAILURE = "DELETE_UNIT_FAILURE";

export const FIND_UNIT_REQUEST = "FIND_UNIT_REQUEST";
export const FIND_UNIT_SUCCESS = "FIND_UNIT_SUCCESS";
export const FIND_UNIT_FAILURE = "FIND_UNIT_FAILURE";

export const FIND_UNITS_REQUEST = "FIND_UNITS_REQUEST";
export const FIND_UNITS_SUCCESS = "FIND_UNITS_SUCCESS";
export const FIND_UNITS_FAILURE = "FIND_UNITS_FAILURE";
